### ISSUE TITLE
No files...

### ISSUE THREAD

**Issue by Mooshimi** [TeamAOF/All-of-Fabric-7#1]
Hello.... where are the mods doe

**Comment by LeakedBuffalo7907** [comment]
AOF7 is in early access for patreon supporters

**Comment by Pdrewicz** [comment]
nah it's broken

**Comment by fridayd** [comment]
It’s less about patreon early access now, that is still happening—really, it’s CF’s new pack approval process being slower than expected. My understanding is when the files go live on the CF page, this repository will reflect what’s there soon after.
