### ISSUE TITLE
[Recipie Conflict] Knife (Croptopia) -> Iron Sai (Simply Swords)

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#10]
https://github.com/TeamAOF/All-of-Fabric-7/assets/87911136/8014a65c-83df-4bb7-b30f-64901566e923

**Comment by Kakiharu** [comment]
That is also the recipe for the Chisel which I came to post about.

**Comment by Kazuhiko-Gushiken** [comment]
Thank you both for letting us know. Currently the mod we use to adjust, balance, and unify recipes is not yet at a stable 1.20.1 state. Once the mod updates, we'll be working on fixing as many recipes as we can!

**Comment by nexusGM** [comment]
The drying rack and the item shelf also conflict.

**Comment by Trent2087** [comment]
Technically fixed in pack version 0.3.0 by adding Polymorph so you can select different recipe outputs when they conflict. Leaving this open as this is a band aid solution until we add Kubejs to fix recipe conflicts.

**Comment by ImAK9** [comment]
Fixed in newer releases
