### ISSUE TITLE
Game Crashes on startup

### ISSUE THREAD

**Issue by FubyCutie** [TeamAOF/All-of-Fabric-7#107]
[latest.log](https://github.com/TeamAOF/All-of-Fabric-7/files/14074740/latest.log)
[hs_err_pid7712.log](https://github.com/TeamAOF/All-of-Fabric-7/files/14074742/hs_err_pid7712.log)
Upon rendering the JVM crashes, attempted fixes:

- remove sodium and dependants
- update sodium and remove dependants
- remove OpenLoader
- remove FancyMenu
- remove ImmediatelyFast
- remove Runtime Resource Pack
- remove Supplimentaries

These were all the mods I could think of that may interact with the JVM directly and cause this crash, other attempts:

- running with java 21
- running with both openjdk and regular java
- running with env __GL_THREADED_OPTIMIZATIONS=0
- rebooting

none of the above fixes worked, nor changed the error (removing sodium minorly changed the stack trace in the core dump, but did not fix it)

**Comment by Linguardium** [comment]
thats actually a linux glfw bug. did you try running with a 1024 resolution?

**Comment by FubyCutie** [comment]
I searched many many different threads like that, finally got it to work by updating LWJGL and nothing else, I tried that quite early on actually, but because I did it at the same time as something else, it broke

**Comment by FubyCutie** [comment]
fix for me: update LWJGL to version 3.3.2, do not use native GLFW installation

**Comment by SubordinalBlue** [comment]
Glad you got it sorted; iirc, that's almost always the fix when LWJGL on Linux issues come up.
