### ISSUE TITLE
Spectrum quests spelling mistakes

### ISSUE THREAD

**Issue by elaniquilador01** [TeamAOF/All-of-Fabric-7#119]
Toxic Reeds!: releaved instead of revealed in quest description
Colored Saplings: Aces instead of Faces when hovering over the quest
Abyssmal: Find out was lies instead of what lies
Remnants of the past: Fortgotten instead of forgotten while hovering
Yet Another's Requim: should be Requiem
Very Boring: Stumple instead of stumble while hovering
Complete spectrum:lategame/collect_myceylon: name change
Acquire: spectrum:crystallarieum: name change

**Comment by ImAK9** [comment]
fixed in newer pack releases
