### ISSUE TITLE
[Suggestion] Achievement for having all diet types at 100% at the same time

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#12]
![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/87911136/d0f862ba-05c5-44ed-9d27-30cb432bf0ad)

Simple suggestion, cause it would be funny if there was an achievement similar to "How did we get here?"

**Comment by SubordinalBlue** [comment]
Interesting idea.
Might help players confused by that mod's UI, thinking it's meant to be a _good_ thing to have full sugar. Maybe better addressed in a quest item.

**Comment by SubordinalBlue** [comment]
Closing this old issue for now.

Still a good suggestion, imho... probably best to make it a suggestion on that mod's repo.
