### ISSUE TITLE
Chipped not working

### ISSUE THREAD

**Issue by WestphalJonas** [TeamAOF/All-of-Fabric-7#120]
Chipped workstations do not work anymore after the UI update of the mod.

![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/14896592/8216b0f2-0647-45f8-999f-5dcccb9df7d5)

**Comment by WestphalJonas** [comment]
Version 3.0.4 seems to fix it partialy. Carpenters table works with oak logs, but stone still doesnt work in the mason table. Havent tested more blocks

**Comment by SubordinalBlue** [comment]
Closing as outdated. [as of this comment, AoF7 2.2.3 includes Chipped 3.0.6.]

If this is still a current problem for you, please post a comment below.
