### ISSUE TITLE
Worlds with the same name always have the same seed

### ISSUE THREAD

**Issue by Biggieglass** [TeamAOF/All-of-Fabric-7#124]
if you make 2 worlds both called "new world" the second one is guaranteed to have the same seed as the first one every time, regardless of what seed you put in.

**Comment by SubordinalBlue** [comment]
Interesting. Does that happen if you restart Minecraft in between creating two worlds withe same name?

**Comment by SubordinalBlue** [comment]
Closing. Whatever it was, it's not happening in current version (just tested).
