### ISSUE TITLE
Crash on startup 1.3.2: Incompatible mods found

### ISSUE THREAD

**Issue by jbolduan** [TeamAOF/All-of-Fabric-7#128]
I upgraded my server and client, server seems to have started okay but client failed to load.  I deleted and recreated the profile in the FTB app and it still doesn't launch giving an incompatible mods found error from the fabric loader.  This is the copy/paste from the fabric mod loader error:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.8+mc1.20.1 with version 0.5.8 or version 0.5.9 that is compatible with:
		 - supplementaries 1.20-2.7.32
More details:
	 - Mod 'Sodium' (sodium) 0.5.8+mc1.20.1 is incompatible with version 1.20-2.7.32 or earlier of mod 'Supplementaries' (supplementaries), but a matching version is present: 1.20-2.7.32!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by SubordinalBlue** [comment]
Somehow either your server or client upgrade did not go right.

Have you tried again?

Closing this issue, but please feel free to open again if needed.

Also, the AOF discord is a good place to find some help with issues adjacent to the pack itself, such as a loader not upgrading the pack properly. (not sure that's what happened here; just an illustrative example.)
