### ISSUE TITLE
Crushing wheels make mercury stone

### ISSUE THREAD

**Issue by Atyneton** [TeamAOF/All-of-Fabric-7#135]
Hi I don't know why but when I crush deepslate iron ore I keep getting mercury cobblestone when crushed with the crushing wheels. its not frequent but its enough to clog things up, I don't believe this is intentional as REI shows no recipe to create this. 

- Aegis

**Comment by Linguardium** [comment]
https://github.com/AlmostReliable/almostunified/issues/51

Looks like its time for this niche issue to be resolved by the pack devs as was decided by the counsel of packdevs, AOF included

**Comment by ImAK9** [comment]
Fixed in 2.0 releases and beyond
