### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by craigygl** [TeamAOF/All-of-Fabric-7#136]
when starting the pack on version 1.3.2 it crashes with a EXCEPTION_ACCESS_VIOLATION. tried with a fresh install of the mod pack and even a fresh install of win11 with no luck any ideas? have also tried with lastest and older graphics drivers

**Comment by Linguardium** [comment]
post your hs_err file and latest.log, and crashlog if it exists

**Comment by craigygl** [comment]
No probs here you go not sure about the crashlog file couldn't find it 
[latest.zip](https://github.com/TeamAOF/All-of-Fabric-7/files/14324498/latest.zip)
[hs_err_pid9080.zip](https://github.com/TeamAOF/All-of-Fabric-7/files/14324499/hs_err_pid9080.zip)

**Comment by SubordinalBlue** [comment]
Crash logs are found in an instance's `crash-reports` folder.

OP, please feel free to open a new issue if you're still having this problem and can post a rash log of it.

Closing: 2 months old, needs crash log to diagnose.
