### ISSUE TITLE
[Bug] I don't even have an explanation for this. But please don't fix it LMFAO (Permanently in elytra state and then permanentally in swiming in the air without elytras until reconnection???)

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#14]
This happened randomly during one of my streams, it truly was an amazing time messing around with it for a bit, as much as this is probably a very problematic bug, I'd really like it to be acknowledged and not be fixed because god damn it is it funny.
https://www.youtube.com/live/ydwlISyjem4?si=9aF8fe0q-tNPkLPQ&t=14286

Glitch seem to have started here
https://www.youtube.com/live/ydwlISyjem4?si=jLeBLSxv0tR7guQQ&t=13585

(All the links have timestamps and they're very important obviously)

**Comment by SubordinalBlue** [comment]
Closing as stale, for now.
Feel free to re-open if it's still an issue.
