### ISSUE TITLE
[Bug] Modern Industrialization hatches

### ISSUE THREAD

**Issue by playfu01** [TeamAOF/All-of-Fabric-7#15]
if u want to add a hatch to Modern Industrialization multi block minecraft crashes.

**Comment by James103** [comment]
Do you have the crash report? If so, can you please post it here/

**Comment by playfu01** [comment]
[crash-2023-08-28_18.00.15-client.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12457084/crash-2023-08-28_18.00.15-client.txt)

**Comment by James103** [comment]
Will you please try updating Modern Industrialization to version 1.7.3 or later, as that version should fix the crash?

**Comment by playfu01** [comment]
i updated it and it doesnt crash anymore.
thanks

**Comment by Trent2087** [comment]
Was fixed in pack version 0.3.0
