### ISSUE TITLE
Missing Shebang in serverstarter.sh

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [TeamAOF/All-of-Fabric-7#154]
The shebang (!#/bin/bash) is missing from the serverstarter.sh script in version 1.3.2

**Comment by SubordinalBlue** [comment]
Not strictly necessary, and in this case... [checks commit history...] hasn't been there in years.

Just pass the script as an argument to calling the shell: `sh serverstarter.sh`.

**Comment by DisruptionSystemsINC** [comment]
> Not strictly necessary in the general case of shell scripts, and in this case... [checks commit history...] hasn't been there in years.
> 
> Just pass the script as an argument to calling the shell: `sh serverstarter.sh`.

This is less than optimal practice.

**Comment by SubordinalBlue** [comment]
Makes 0 difference, really.

Except this way, the script file does not need execute permission set.
