### ISSUE TITLE
Indrev broken textures

### ISSUE THREAD

**Issue by elaniquilador01** [TeamAOF/All-of-Fabric-7#157]
Standing slightly far away from Indrev machines and looking north makes them invisible on one side, standing close to them the same side looks darker than other sides
Also the lazuli flux containers have flickering textures on some faces where the output arrow is
Some examples of the missing arrow, the invisible faces and a comparison of the color of the sides:
![2024-02-23_15 34 03](https://github.com/TeamAOF/All-of-Fabric-7/assets/153564964/8ad7d0f9-2cd2-4ba3-ac6d-f4a71909bfa8)
![2024-02-23_15 34 09](https://github.com/TeamAOF/All-of-Fabric-7/assets/153564964/92c682b7-fbe2-4a44-8c7b-612f00450a69)
![2024-02-23_15 36 28](https://github.com/TeamAOF/All-of-Fabric-7/assets/153564964/d15b887c-1ad1-4275-980c-b815cea72c38)
![2024-02-23_15 36 51](https://github.com/TeamAOF/All-of-Fabric-7/assets/153564964/b9163997-c7ee-4047-97f4-eff2b5e7b7f4)
![2024-02-23_15 34 44](https://github.com/TeamAOF/All-of-Fabric-7/assets/153564964/2ed3c463-da38-4533-9023-48b176cf8d04)
![2024-02-23_15 34 46](https://github.com/TeamAOF/All-of-Fabric-7/assets/153564964/8589f278-7a3f-4f61-b91a-eab5da2740dc)
![2024-02-23_15 36 01](https://github.com/TeamAOF/All-of-Fabric-7/assets/153564964/66d55309-03ff-41a9-afb2-2f7a44178509)

**Comment by Linguardium** [comment]
be sure to report this to the mod dev, as well https://github.com/GabrielOlvH/Industrial-Revolution/issues
