### ISSUE TITLE
[Bug] Crash while rendering a certain item in Creative Menu or otherwise

### ISSUE THREAD

**Issue by FevilGitHub** [TeamAOF/All-of-Fabric-7#17]
Hey! I was just looking through the creative menu when i clicked on one of the tabs (Immersive Armors) and the game crashed on the spot. Turns out it was bc it failed to render an item.

EDIT: Apparently its literally Sodium and it doesnt actually crash bc of the creative menu. Im not too tech savvy but i have seen a previous issue cause the same thing for some reason. Cant wait for the next update!

Crash Report: https://pastebin.com/xXwWkhu9

**Comment by SubordinalBlue** [comment]
Stale issue; AoF7 has moved on from Sodium since.
