### ISSUE TITLE
[Suggestion] Client Mods

### ISSUE THREAD

**Issue by LoboMetalurgico** [TeamAOF/All-of-Fabric-7#19]
Update Sodium
Update Iris
Update Indium
Update Reese's Sodium Options

Add Sodium-Extra
Add LambDynamicLights

**Comment by Trent2087** [comment]
Sodium has to be downgraded until Create/Sodium compatibility is supported in the newer version. It will be updated when that happens.

**Comment by LoboMetalurgico** [comment]
Oh, right. But still, I think it would be good to add Dynamic Lights and Sodium-Extra (Sodium-Extra allows you to disable animations/particles, which can drastically improve your FPS)
