### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by frazer025** [TeamAOF/All-of-Fabric-7#202]
crashes when starting the game with an error
[crash log.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/14623345/crash.log.txt)

**Comment by Natanaelel** [comment]
OutOfMemoryError: Allocate more ram to your instance. 6-8 gigs should be enough.

**Comment by ImAK9** [comment]
Like the comment above, you're low on RAM.
