### ISSUE TITLE
Flat bedrock is not friendly with Spectrum

### ISSUE THREAD

**Issue by truepurpledino** [TeamAOF/All-of-Fabric-7#203]
Flat Bedrock has been added to AOF7 and I think that considering Spectrum being in my opinion an important part of the modpack, it should not have been added since it messes with the **(spoilers->)** drop of bedrock dust from bedrock. When breaking bedrock that is on the first layer (and last layer of the world), the bedrock dust does not drop and the bedrock block is instead turned into the portal block to the deep dark, hence making bedrock dust impossible to get in the overworld. This makes it so you can only get the dust from the nether layers of bedrock. This alters the progression and in a mod that is already based on finding out things yourself, making bedrock dust even less intuitive is not the move in my opinion. Hence I recommend removing flat bedrock entirely.

**Comment by truepurpledino** [comment]
https://discord.com/channels/570630340075454474/1137454902625443840/1218720319070797935 this link shows the player experience with this issue.

**Comment by Gronglegrowth** [comment]
Seconded; it messes with the progression of the mod too much to be worth keeping, and effectively breaks progression.

**Comment by ImAK9** [comment]
Agreed, will be removing Flat Bedrock

**Comment by Linguardium** [comment]
cant use nether ceiling?

**Comment by ImAK9** [comment]
Fixed in newer pack releases
