### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by Jyinxe** [TeamAOF/All-of-Fabric-7#205]
I am playing the updated mod for the first time and I am not able to get into any of the boats

**Comment by SubordinalBlue** [comment]
Uh oh. Is it still bugged for you?
Feel free to bump this issue (with a new comment) tomorrow if no one's addressed it by then. I hope to do so, but looking at a busy day ahead of me.

**Comment by SubordinalBlue** [comment]
Closing, as I'm unaware of any similar reports.
I assume, and certainly hope, op has figured out what was going wrong.
