### ISSUE TITLE
[Mod Incompatibility] Calibrated Access unusable

### ISSUE THREAD

**Issue by hokomili** [TeamAOF/All-of-Fabric-7#21]
The Interface immediately closes when using on a container(chest or barrel), and it doesn't support many modded blocks.
acikek/calibrated-access#02

**Comment by acikek** [comment]
Aware. Been working on it for awhile, specifically extracting the reaching logic into a more stable library.

The issue you linked is unrelated to this pack, the incompatibility here is with Pehkui

**Comment by acikek** [comment]
Should be fixed now

**Comment by ImAK9** [comment]
fixed in newer releases
