### ISSUE TITLE
[Bug Report]: Server Crash

### ISSUE THREAD

**Issue by greenbud12** [TeamAOF/All-of-Fabric-7#211]
### Modpack Version

2.0.1

### Describe your issue.

The issue seems to stop occurring over time but will happen again when a new player joins. It is the same error that had happened four times now over the course of six hours. 

### Crash Report

https://gist.github.com/greenbud12/467221a9048ce013414c3fab8a5d21cd

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

greenbud12

**Comment by Linguardium** [comment]
known issue with the werepyre from besmirchment. It has been fixed in the latest version of besmirchment and should be fixed in the next aof7 release

**Comment by greenbud12** [comment]
Awesome, I will close this then.
