### ISSUE TITLE
[Bug Report]: Bewitchment

### ISSUE THREAD

**Issue by LunaDarkness** [TeamAOF/All-of-Fabric-7#212]
### Modpack Version

2.0.1

### Describe your issue.

I was just planting crop's on my farm without warning, freezing, or stuttering the game crashed and I read the crash report telling me bewitchment gave an error I've never seen before.

### Crash Report

<script src="https://gist.github.com/LunaDarkness/ecfc7d2941e33be26d5a011db9dcb724.js"></script>

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

roseofdarkness

**Comment by Linguardium** [comment]
known issue. reported to the besmirchment dev and they released a new version of besmirchment to fix it. the next AOF7 update should have the new besmirchment version.

**Comment by sunsushishine** [comment]
+++

**Comment by Linguardium** [comment]
@sunsushishine  no point adding useless comments. The issue was already solved. if you have something productive to add, please do. otherwise "me too" comments do nothing to progress the issue

**Comment by ImAK9** [comment]
Fixed in 2.0.2
