### ISSUE TITLE
[Bug Report]: Significant FPS drop in latest release

### ISSUE THREAD

**Issue by Linguardium** [TeamAOF/All-of-Fabric-7#214]
### Modpack Version

2.0.1

### Describe your issue.

Many graphics cards are affected heavilty by the way mc animates textures. the fix to this traditionally has been to disable rendering animations that were not visible. The latest version of the pack causes issues due to https://github.com/TeamAOF/All-of-Fabric-7/commit/9a068578853b9903eeee768121403717ff0e89da forcing the setting back off.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by ImAK9** [comment]
This feature has been re enabled with the 2.0.2 update of AOF7
