### ISSUE TITLE
[Bug Report]: backpack from traveler's backpack not opening

### ISSUE THREAD

**Issue by AZURQXX** [TeamAOF/All-of-Fabric-7#216]
### Modpack Version

fabric-0.15.7

### Describe your issue.

i crafted the backpack and equipped it but when i press the open button it will not open 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Linguardium** [comment]
check your keybinds. by default travelers backpack keybind conflicts and you will need to clear out or reassign the keybinding
