### ISSUE TITLE
[Bug Report]: Rendering Supplementaries block causes crash

### ISSUE THREAD

**Issue by NanoBaker** [TeamAOF/All-of-Fabric-7#217]
### Modpack Version

1.3.2

### Describe your issue.

Whenever approaching a certain player's base, that user will immediately disconnect from the server and have their Minecraft client crash with an error about some supplementaries block. This crash still occurs when downloading the world file and testing it in single player.

### Crash Report

https://gist.github.com/NanoBaker/c15223674189b4bbe86c2173602a9b53

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by SubordinalBlue** [comment]
Yes... this was the April Fool's joke code in Supplementaries going bad; known issue with that mod.
