### ISSUE TITLE
[Suggestion]: Replace Heracles with FTB Quests

### ISSUE THREAD

**Issue by dinkley** [TeamAOF/All-of-Fabric-7#219]
### URL

https://www.curseforge.com/minecraft/mc-mods/ftb-quests-fabric

### Why would you like this mod added?

I enjoyed All of Fabric 6 mostly because it had the team-based questing system, where as long as someone on your team completed the task, you'd all get rewards for it. I was using this as a metric to see which part of the modpack we haven't touched yet, so we could go down that quest path together.

Heracles does not seem to have this ability.

**Comment by Linguardium** [comment]
you are asking the team to complete redo all of the quests that they have nearly finished building...

Also, quest progress should be shared within the same guild. do you have a guild and are you part of the same one?
