### ISSUE TITLE
[Bug] Librarian selling Air for an emerald

### ISSUE THREAD

**Issue by hokomili** [TeamAOF/All-of-Fabric-7#22]
I'm not sure if it's related to the loot problem from another issue...
![2023-09-27_15 54 17](https://github.com/TeamAOF/All-of-Fabric-7/assets/28939939/3d444051-8008-4702-824e-73ea86ce2e7a)

**Comment by SubordinalBlue** [comment]
Closing as stale issue; please feel free to re-open if it's still affecting the current pack version.
