### ISSUE TITLE
[Bug Report]: Item Entity claim bypass in the wrong folder

### ISSUE THREAD

**Issue by Linguardium** [TeamAOF/All-of-Fabric-7#220]
### Modpack Version

2.0.2

### Describe your issue.

https://github.com/TeamAOF/All-of-Fabric-7/tree/main/kubejs/data/cadmus/tags/entities

https://minecraft.wiki/w/Tag#Java_Edition

it should be `entity_types` not `entities`

### Crash Report

nah fam

### Latest Log

still no

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Linguardium

**Comment by trunksbomb** [comment]
https://discord.com/channels/570630340075454474/1225275191345549403/1225275191345549403

I hear Trent is to blame, if that's even his real name.

**Comment by Linguardium** [comment]
well, at least someone is trying to fix these issues smh my head https://github.com/TeamAOF/All-of-Fabric-7/commit/6c4461bfe47fd4b3ea88efd78802b696085a984e

**Comment by Trent2087** [comment]
Fixed in next release. Thanks!

**Comment by SubordinalBlue** [comment]
Fixed with c328d23
