### ISSUE TITLE
Server Files Not Generating?

### ISSUE THREAD

**Issue by hunterroy** [TeamAOF/All-of-Fabric-7#222]
Sorry if this isn't the right place to ask, seeing as it's server issues and not the pack itself, I'm not sure where to ask.

I've never had an issue running servers before on AOF5 and 6. Now all of the sudden trying to run the startserver.bat file after unzipping the server pack from CF gives me this readout in the CMD window:

**serverstarter binary not found, downloading serverstarter...
Unable to create job - 0x80200049
The job count for the current user has exceeded the per-user job limit.

Error: Unable to access jarfile serverstarter-2.4.0.jar
Press any key to continue . . .**

Is it something with the Modpack Profile? is there somewhere else I can grab the needed jar?

**Comment by Linguardium** [comment]
this may be related to windows update. the error you are getting is coming from Windows itself. You can download the serverstarter-2.4.0 jar from https://github.com/TeamAOF/ServerStarter/releases/download/v2.4.0/serverstarter-2.4.0.jar

**Comment by hunterroy** [comment]
That's what I was looking for but couldn't find it for life of me, appreciate it!
