### ISSUE TITLE
[Bug Report]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode

### ISSUE THREAD

**Issue by str4ydog** [TeamAOF/All-of-Fabric-7#225]
### Modpack Version

2.0.2

### Describe your issue.

I can play fine on singleplayer, but whenever i try to start my server it shows this error: "Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode"
I don't even have datapacks

### Latest Log

https://gist.github.com/str4ydog/6b978cd06a901b6fe99b939ac3517f05

### Have you modified the modpack?

Yes

### User Modifications

Hearth and home, restart server, mc2discord, vanish mod, item filters, skinlayers3d, ftb essentials, diamond economy, diamond auction house, amemdments, i think these are the only ones that i added so far as i can remember

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

str4ygod

**Comment by Linguardium** [comment]
does the server work if you use the default server pack and dont modify it?

**Comment by str4ydog** [comment]
it works without any modifications

**Comment by Linguardium** [comment]
then it must be one of your mods.
