### ISSUE TITLE
[Bug] Copper Quadruplication

### ISSUE THREAD

**Issue by hokomili** [TeamAOF/All-of-Fabric-7#23]
Cut copper can be turned into 4 cut copper.
![2023-09-27_15 55 37](https://github.com/TeamAOF/All-of-Fabric-7/assets/28939939/2b7f4fa4-a420-4a05-951e-04477b77acd0)

**Comment by Kazuhiko-Gushiken** [comment]
@hokomili are you sure this isnt just your instance? i dont seem to see it here 
![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/132615999/a672504e-6de2-423f-b3a7-502c2737f5f3)

**Comment by ImAK9** [comment]
I fixed this issue a bit ago, forgot to close it.
