### ISSUE TITLE
[Bug Report]: Meadow mod disables rendering variants if MoreMobVariants mod is present

### ISSUE THREAD

**Issue by Linguardium** [TeamAOF/All-of-Fabric-7#234]
### Modpack Version

2.1.2

### Describe your issue.

Sheep appear white but are actually Lets Do: Meadow variants. The clientside mixins that allow them to render differently are disabled when More Mob Variants is present, causing them to appear "normal" but causing them to still drop their changed wool.

Lets Do Meadow doesnt have an issue tracker and requires people to join their discord to report issues. I wont do that so i am reporting the modpack issue to the modpack devs so they can handle it however they want

### Crash Report

no

### Latest Log

no

### Have you modified the modpack?

No

### User Modifications

no

### Did the issue happen in singleplayer or on a server?

Both

**Comment by ImAK9** [comment]
Fixed in 2.2.0 and above
