### ISSUE TITLE
[Bug Report]: Create Mod Backtank

### ISSUE THREAD

**Issue by FRZYEFFECT** [TeamAOF/All-of-Fabric-7#239]
### Modpack Version

2.1.2

### Describe your issue.

I have 3 copper backtanks but it will not give me the achievement. It is the last thing I need to get 100% on that mod. I have made 2 and been gifted 1 and still nothing. Someone else in the server tried and it would not allow him to get the achievement either.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

frzyeffect

**Comment by SubordinalBlue** [comment]
You need a fully pressurized backtank to complete that task.

**Comment by FRZYEFFECT** [comment]
it worked thank you didnt realized it had to be fully filled
