### ISSUE TITLE
Crashed upon launching a new world

### ISSUE THREAD

**Issue by 12foot12** [TeamAOF/All-of-Fabric-7#25]
[crash-2023-10-05_10.53.27-server.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12821658/crash-2023-10-05_10.53.27-server.txt)

**Comment by Natanaelel** [comment]
remove the mod [WoodsAndMires](https://github.com/Juuxel/WoodsAndMires)

**Comment by ImAK9** [comment]
Fixed in 0.5.1
