### ISSUE TITLE
[Bug Report]: Pebblehost Server crashes when loading bumblezone

### ISSUE THREAD

**Issue by jacobcshort78** [TeamAOF/All-of-Fabric-7#254]
### Modpack Version

2.2.2

### Describe your issue.

Upon entering the bumblezone, our server crashes in seconds. Per the mod developer, it pertains to an issue with a Hephaestus mixin called Star -- is there a fix for this yet?

### Crash Report

https://pastebin.com/1DvAFsEK

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Ludus

**Comment by SubordinalBlue** [comment]
The Hephaestus mod was updated in pack version 2.2.3... are you still experiencing that issue with that pack update?

Closing as outdated.
If this is still a current problem for you, please post a comment below.
