### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by 402391** [TeamAOF/All-of-Fabric-7#257]
### Modpack Version

2.2.3

### Describe your issue.

Uppon entering a certain area the server crashed. Seems to be a problem with an entity loading?\
TLDR of the crash report:
Description: Feature placement
We are asking a region for a chunk out of bound
dev.hexnowloading.dungeonnowloading.world.features.entities.SkeletonSpiderJokeyFeature.method_13151(SkeletonSpiderJokeyFeature.java:26)
(i think that that line might be the issue but i dont have a lot of experience in Java)

### Crash Report

https://gist.github.com/402391/f2b20bead16ccef0361ea211d7514b9d

### Latest Log

i dont have it unfortunetly

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

user:402391

**Comment by SubordinalBlue** [comment]
Seems like maybe your server's config files didn't get properly updated to the 2.2.3 version.

The file, "sophisticatedbackpacks-server.toml", at line 357, should have the chance of an entity spawning with a Sophisticated Backpack set to 0.

<img width="572" alt="image" src="https://github.com/TeamAOF/All-of-Fabric-7/assets/6677700/8176193e-33ef-4b8e-a8b2-5d0b8667e96f">

**Comment by SubordinalBlue** [comment]
Actually, your crash log shows the server is missing two mods added by, and still has one removed, in 2.2.3.

Seems that server is running 2.2.2.
