### ISSUE TITLE
Please update Sophisticated mods

### ISSUE THREAD

**Issue by ArceusX99** [TeamAOF/All-of-Fabric-7#259]
### Describe your suggestion

The Sophisticated Core, Backpacks, and Storage are all on old snapshot versions with many bugs that crash or don't work with AE2 systems. Specifically, using a storage bus on a Storage Controller and then trying to take items in/out from an AE2 Terminal will make everything in the terminal disappear until world re-load. Using an AE2 export bus to export items from a Sophisticated Storage system will crash the game also. Using a Coxinha Utilities Cardboard Box on any Sophisticated Storage container with upgrades will temporarily make the items inaccessible/no numbers until you update the upgrade slots.

### Why would you like this added/changed?

A simple update will probably fix this.

**Comment by SubordinalBlue** [comment]
Perhaps you are confusing Fabric and (Neo)Forge? The All of Fabric series of modpacks uses only Fabric-based mods.

[ Recently it was announced publicly on the [All of Everything discord](https://discord.gg/6rkdm48) that a NeoForge modpack, similar in concept to All of Fabric, is planned for the 1.21 era of Minecraft ]

All of Fabric 7 does, currently, have the latest versions of Sophisticated Core, Backpacks, and Storage _that are available for Fabric_:

https://www.curseforge.com/minecraft/mc-mods/sophisticated-core-unofficial-fabric-port
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks-unofficial-fabric-port
https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage-unofficial-fabric-port

**Comment by EugeneLagonski** [comment]
It's fixed.
https://github.com/Salandora/SophisticatedStorage/issues/10
Tested it on the new version. The only question I have is whether it should accept items which are not in chests.

**Comment by SubordinalBlue** [comment]
Updated with latest pack release, 2.3.0.

**Comment by Salandora** [comment]
Oh no I'm too late!
I was just informed through a comment on curseforge that there is a massive bug with one of the fixes in the last update.
It leads to a full inventory wipe and crash, and because it is is sophisticated core it affects backpacks and storage.
I'll still investigating and will push a hotfix as soon as possible.

**Comment by SubordinalBlue** [comment]
Uh... cool! Can get a theme-update out that a certain anonymous doofus forgot to take of earlier. xD

**Comment by Salandora** [comment]
FYI I just released the bugfix.

**Comment by SubordinalBlue** [comment]
Thank you; will be keeping an eye out for it to hit CF, so it can be included in the next pack update.

Will just updating Sophisticated Core be enough, or will all three need to be updated to avoid the bug?

**Comment by Salandora** [comment]
SophisticatedBackpacks also got a fix included for another incompatibility with repurposed structures.

So Backpacks and Core would both be needed.

But to avoid confusions I did reupload all 3 mods to keep build numbers in line. 

So I suppose updating all 3 would be best.
