### ISSUE TITLE
[Bug Report]: Can't make Blazing Chili in AOF7 2.2.3

### ISSUE THREAD

**Issue by trunksbomb** [TeamAOF/All-of-Fabric-7#260]
### Modpack Version

2.2.3

### Describe your issue.

I can't make blazing chili, and I assume it's because that empty slot is something missing. On v2.2.3

![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/1904331/347cd9aa-5600-4796-bfd2-5520feba709c)

Happens with the Create Mixer and the Farmer's Delight Cooking Pot. Also happens with the recipe that's supposed to make chili as a fluid.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

trunksbomb

**Comment by SubordinalBlue** [comment]
Fixed; was bugged only on NA7.
