### ISSUE TITLE
[Bug Report]: Certus cluster missing recipes

### ISSUE THREAD

**Issue by troyheady2** [TeamAOF/All-of-Fabric-7#262]
### Modpack Version

2.3.3

### Describe your issue.

certus quartz cluster does not have any recipes for create crushing wheel or any other tech mod pulverizer / macerator.
Manual placing and breaking are only way to convert clusters to crystals.

### Have you modified the modpack?

Yes

### User Modifications

added the following mods to pack:

BotanyPots-Fabric-1.20.1-13.0.31.jar        
peripheralium-fabric-1.20.1-0.6.15.jar      
worldedit-mod-7.2.15.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar 
smallships-fabric-1.20.1-2.0.0-b1.1.jar
dankstorage-fabric-1.20.1-9.jar             
turtlematic-fabric-1.20.1-1.3.0.jar

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

vakermit

**Comment by SubordinalBlue** [comment]
The intended way to harvest certus quartz crystal is with ae2's own annhilation plane, not with Create.
Create is good for milling or crushing certus quartz crystals into certus quartz dust, though. Or bulk blasting that dust into Silicon.

(totally unrelated, but I am curious why add _danks_? Have you tried the _banks_ that are in the pack, and meant to be a replacement for danks?

**Comment by SubordinalBlue** [comment]
Agreed on cross mod interactions being the bee's knees!

This particular case, imho, is the way it should be.

If one really wanted to use Create to harvest certus quartz crystals, a deployer wielding a pickaxe could be used. Would have to get clever with red stone and timers, maybe observers too, to have the deployer only break the crystals once they are fully grown.

Cheers.
