### ISSUE TITLE
[0.5.1] Rendering Block Entity crash for MI Steel Furnace

### ISSUE THREAD

**Issue by fridayd** [TeamAOF/All-of-Fabric-7#27]
Originally reported by Nitrofenix on AoF discord: https://discord.com/channels/570630340075454474/1160203242450468934

Also confirmed it myself. World will crash upon entry thereafter, of course.

[crash-2023-10-08_10.18.32-client.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12839541/crash-2023-10-08_10.18.32-client.txt)

**Comment by fridayd** [comment]
I repeated the experiment with a different MI block, the bronze mixer, for another data point. Same result.
[crash-2023-10-08_10.44.17-client.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12839562/crash-2023-10-08_10.44.17-client.txt)

**Comment by ImAK9** [comment]
Fixed in 0.5.1
