### ISSUE TITLE
My server stop working when myself join in.  Seeking Helps!

### ISSUE THREAD

**Issue by 1SuPaul** [TeamAOF/All-of-Fabric-7#270]
### Modpack Version

2.2.3

### Describe your issue.

[crash-2024-06-15_13.23.28-server.txt](https://github.com/user-attachments/files/15845793/crash-2024-06-15_13.23.28-server.txt)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Paul su#5809

**Comment by Leonxilofin** [comment]
Probably not the intended way to fix the problem but you could try installing neurina https://www.curseforge.com/minecraft/mc-mods/neruina/files/5361849 so you can login without crashing and when your in removing the amethyst golem at 175.98, 25.00, -11.79

**Comment by 1SuPaul** [comment]
Thank you for ur suggestion,I'll do it and tell u the result. :))

**Comment by SubordinalBlue** [comment]
After following that good suggestion, I'd recommend changing the Amethyst Golem spawn chance to `0`, in "config/adventurez.json5"... that's happening in the next pack update anyhow.

**Comment by 1SuPaul** [comment]
I'm sure I'll do it,thank you so much for helping me out!

**Comment by 1SuPaul** [comment]
After testing,my server is working perfectly fine at the moment. Thank you very much for your help! If I got any type of crashes on this modpack,may I ask for your help again?

**Comment by SubordinalBlue** [comment]
Of course. Here is good, but also the AOE discord's #support and #bug-report channels are great.
