### ISSUE TITLE
[Bug Report]: AE system stops receiving power

### ISSUE THREAD

**Issue by wiblu** [TeamAOF/All-of-Fabric-7#275]
### Modpack Version

2.3.0

### Describe your issue.

AE system had been working fine before updating pack, now if i add any component to the network it stop receiving power until it stops working, have tried adding energy cells incase it was a spike but didn't help, tried energy accepter instead of straight into controller, tried different power cables but the only thing that lets it accept power again is breaking all the controllers 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
What pack version did you update from?

In addition to AE2 itself, there a few AE2 related mods in the pack.

- Applied Energistics 2
- Applied Botanics
- Polymorphic Energistics
- AE2WTLib
- AE2 + Mouse Tweaks Fix
- ExtendedAE
- MEGA Cells

Among those, going from 2.2.3 to 2.3.0, only ExtendedAE had an update.

Another thing to look for: any messages related to AE2 in your latest log?

**Comment by wiblu** [comment]
Just the last update 2.2.3
Since loading up again after last nights rage quit it is back to working properly, might have been some issue on my end.
But the last thing I did before it started having issues was start an auto craft using ExtendedAE but the crafts are fine now so not sure.
Couldn't see anything AE2 related in log only GL ERROR
