### ISSUE TITLE
[Bug Report]: Can't set combined keybinds after the last update (MacOS)

### ISSUE THREAD

**Issue by EugeneLagonski** [TeamAOF/All-of-Fabric-7#280]
### Modpack Version

2.4.0

### Describe your issue.

I can't set combined keybinds after the update. For example, I can't set CMD + B, SHIFT + B for different backpacks. Wasn't an issue with [Modern KeyBinding [Fabric]](https://www.curseforge.com/minecraft/mc-mods/modern-keybinding-fabric).
OS: MacOS 14.5

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

guiscardqq

**Comment by shadowpather** [comment]
I reported this on the discord earlier along with a client side fix:

> With the 2.4.0 update, noticed I could set my keybinds correctly using the newly installed Amecs. Controlling was the issue.
> If controlling is installed, you can't change keybinds to combination of keys, negating the whole point of it.
> If controlling is removed, Amecs behaves and has its own search field for keybinds.

**Comment by EugeneLagonski** [comment]
> I reported this on the discord earlier along with a client side fix:
> 
> > With the 2.4.0 update, noticed I could not set my keybinds correctly using the newly installed Amecs. Controlling was the issue.
> > If controlling is installed, you can't change keybinds to combination of keys, negating the whole point of it.
> > If controlling is removed, Amecs behaves and has its own search field for keybinds.

Thank you for the solution. Now I can set shift, control, and alt combinations, but can't set cmd(windows) combinations. It's still an issue.

**Comment by shadowpather** [comment]
Looking into Amacs, both the mod description and configuration file indicate that it supports only control, alt, and shift for the key combinations. The file "options.amecsapi.txt" appears to hold 3 boolean values for each of those keys. While it would be nice if the mod supported it, this is less of a mod issue and more of a missing feature.

**Comment by ImAK9** [comment]
Fixed in 2.4.1
