### ISSUE TITLE
v0.6.3: With shaders on, mob's appear as emissive when player holds a torch

### ISSUE THREAD

**Issue by SubordinalBlue** [TeamAOF/All-of-Fabric-7#29]
Confirming a report from discord.

Tested with a cow and trader llama.

**Comment by SubordinalBlue** [comment]
Tested with 0.6.3. Updated issue title accordingly.

**Comment by dovydasvy** [comment]
The issue disappears, at least for me, when I change "RP Support" from "Integrated PBR+" to "Basic".

**Comment by SubordinalBlue** [comment]
Good to know.

7 hasn't been able to move to the latest Sodium yet (iirc, there's a hang up involving Create on Fabric)... hopefully this will resolve when it can move to the latest Sodium.

I really just filed this issue to as something to keep an eye on.

**Comment by SubordinalBlue** [comment]
Tardy to get back and check this. All looks good me now, when using shader settings like I did when first reporting this.

Closing.
