### ISSUE TITLE
[Bug Report]: my server problems

### ISSUE THREAD

**Issue by Shironeko0o** [TeamAOF/All-of-Fabric-7#294]
### Modpack Version

2.4.5

### Describe your issue.

my AOF7 server tps always low becuz MSPT is 100 or above but player only 8
i used spark to find but it show it was entity problem 
how can i fix it

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by zerojay** [comment]
You've given next to nothing to give you any help with. What specifications are the hardware you are running the server on, for instance?

**Comment by Shironeko0o** [comment]
i5 12400KF and 16G DDR43200ram

**Comment by Shironeko0o** [comment]
What information should i give u else?

**Comment by Gronglegrowth** [comment]
A link to a Spark report would provide plenty of information.

**Comment by Shironeko0o** [comment]
https://spark.lucko.me/DcAnJbi5cM
