### ISSUE TITLE
Unable to launch server (and client) despite using serverstarter

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#3]
Log attached:
[AOF7.log](https://github.com/TeamAOF/All-of-Fabric-7/files/12397137/AOF7.log)
I can't launch the game either client side but that's a separate matter talked about below.
Server specs stuff and etc:
[cpuinfo.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12397146/cpuinfo.txt)
```
root@TheSirioNAS-A6:/smb/sirio-raid/System/SGN-MC/AOF7# java -version
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
root@TheSirioNAS-A6:/smb/sirio-raid/System/SGN-MC/AOF7# hostnamectl
 Static hostname: TheSirioNAS-A6
       Icon name: computer-desktop
         Chassis: desktop 🖥️
      Machine ID: d88005f697494612affc969db4a0bbfa
         Boot ID: 90e5906541e844c4b06ea0c43a0b24f9
Operating System: Debian GNU/Linux trixie/sid     
          Kernel: Linux 6.4.0-3-amd64
    Architecture: x86-64
 Hardware Vendor: Gigabyte Technology Co., Ltd.
  Hardware Model: F2A78M-HD2
Firmware Version: FDc
   Firmware Date: Thu 2019-03-07
    Firmware Age: 4y 5month 2w 1d                 
root@TheSirioNAS-A6:/smb/sirio-raid/System/SGN-MC/AOF7#
```
Server files are located on a RAID0 array, server running as root I know, I refuse running as a regular user, and when AOF6 existed, it wasn't a problem, everything worked fine.
Edit: Yes I did try launching without using serverstarter and the same issue happens

Client side:
https://paste.ee/p/0sZMd
^Note I dragged and dropped all the server files to a multi-mc instance, this is probably my fault if it doesn't work but here's the log anyways.

**Comment by Linguardium** [comment]
appears to be a conflict between obscure-api (needed by [Aquamirae](https://legacy.curseforge.com/minecraft/mc-mods/aquamirae-fabric) ) and DML

new DML beta dropped today to fix this. https://www.curseforge.com/minecraft/mc-mods/deep-mob-learning-refabricated/files/4715730

**Comment by ImAK9** [comment]
How do you have DML? It wasnt added.

**Comment by Trent2087** [comment]
Looks like its a .disabled file in the minecraftinstance.json. Which I guess the modlist script still adds. It should not be downloading  with the modpack, and from my instance and the server instance, it is not being downloaded...

**Comment by Linguardium** [comment]
can confirm, does not download with prismlauncher nor with the serverstarter packed files in the release page. I suppose that does bring up the question since it doesnt exist in the manifest files provided by curseforge.

**Comment by SiriusBYT** [comment]
Confirming that the fact that I'm unable to launch the game client side was a me issue, downloaded the modpack via the curseforge app (disgusting, please put all of fabric on modrinth or something for the love of god)
Still can't figure out what's up with the server though, will give reinstalling a shot

**Comment by SiriusBYT** [comment]
Can confirm the serverstarter is completely broken, I drag and dropped all the client files downloaded from curseforge (ew) and the server works

**Comment by Linguardium** [comment]
Can you run a fresh copy of the server pack files from curseforges website and run the bat/sh file and see if there are issues with that? Since you ended up with a mod it doesn't have, I want to make sure you didn't somehow end up with a messed up file

**Comment by SiriusBYT** [comment]
> Can you run a fresh copy of the server pack files from curseforges website in its own empty folder and run the bat/sh file and see if there are issues with that? Since you ended up with a mod it doesn't have, I want to make sure you didn't somehow end up with a messed up file

Curseforge doesn't have the server files yet for some reason, at least at the time as I installed my server, I had to download the files directly from the github repo, will try again when there's a new update out and the server files are indeed there.

**Comment by Linguardium** [comment]
They are posted as additional files in each release https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6/download/4714292

**Comment by SiriusBYT** [comment]
Seems like it works now (v0.2.1)
