### ISSUE TITLE
[Bug Report]: Server Crash on Startup

### ISSUE THREAD

**Issue by Obbs1** [TeamAOF/All-of-Fabric-7#301]
### Modpack Version

2.4.5

### Describe your issue.

Server almost gets through startup process, spits out some errors, then restarts on loop

### Latest Log

https://gist.github.com/Obbs1/b3fd2c5a94712e6ca33a893f5dbac0be#file-latest-log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Obbs#0401

**Comment by SubordinalBlue** [comment]
crash log file might be more helpful; that linked log cuts off before the server restarts or crashes.

**Comment by Obbs1** [comment]
Hopefully this helps.

[latest.log](https://github.com/user-attachments/files/16503141/latest.log)

**Comment by Linguardium** [comment]
check for a crash log in the crash-reports folder or an hs_err file in the server's folder

**Comment by Obbs1** [comment]
Is this what you need?
[crash-2024-08-05_16.31.09-server.txt](https://github.com/user-attachments/files/16503460/crash-2024-08-05_16.31.09-server.txt)

**Comment by Linguardium** [comment]
yes, your server is timing out. disable the watchdog by setting max-tick-time to -1 in server.properties and see if it eventually loads. if so, you can adjust the tick time to something smaller like 120000 or 240000

**Comment by Obbs1** [comment]
Alright, thank you. I'll try that out.

**Comment by Obbs1** [comment]
It worked, thank you very much for your time.
