### ISSUE TITLE
[Bug Report]: No mods in server files for 2.5.1

### ISSUE THREAD

**Issue by DaHofa02** [TeamAOF/All-of-Fabric-7#306]
### Modpack Version

2.5.1

### Describe your issue.

If I download the server files from the yaml file there are no mods in there

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by SubordinalBlue** [comment]
There aren't supposed to be.
You need to run the startserver script (.bat for Windows or .sh for macOS and Linux)... it will download the mods for you.

**Comment by DaHofa02** [comment]
oh I found it thx but I found an other problem and this ist that if you want to start the server in linux you have at the end of the day.sh file a dos end of line and not a unix end of file this means you can't start the server this means you need to create a new file with the whole content

**Comment by SubordinalBlue** [comment]
Sure you didn't have that file go through a windows system first?

sidenote: `dos2unix` is a handy utility for converting a file with windows line endings to one with unix endings... no need to make a new file.
