### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by MrPlaner** [TeamAOF/All-of-Fabric-7#317]
### Modpack Version

2.5.2 (newest available)

### Describe your issue.

Hi,

Tried downloading the newest server packs - ran the batch files to download everything.
When server files were ran, Nether Vinery was popping up issues.
When that was removed, some spectrallib started having issues.

Anything I can do to fix this without removing the mods?
I did 0 changes, just ran the server files provided with the modpack through CurseForge.

Thanks.

### Crash Report

https://gist.github.com/MrPlaner/e82bb223a8786419c874ad2c97861d30

### Latest Log

https://gist.github.com/MrPlaner/bb97a9eed42e8ebfd2e728c733be0e61

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Linguardium** [comment]
you are using java23. java23 is not compatible with fabric.

**Comment by MrPlaner** [comment]
Oh shoot, you're right.
Just checked google for the info and yeah, will do a quick re-install and get back here with update.

**Comment by MrPlaner** [comment]
OK, the server loaded perfectly fine, but on join it didn't let me with the below error:

https://gist.github.com/MrPlaner/ec272630fa01d6e19635e7e25167b557

On Client side it just said: "io.netty.util.IllegalReferenceCountException: refCnt: 0" pretty much.

**Comment by Linguardium** [comment]
normally this happens with mismatched server and client pack versions. make sure you didnt remove server mods

**Comment by MrPlaner** [comment]
Nope, it was freshly run server batch, deleted everything it did and ran it to re-download everything.

The CurseForge instance of the Client was also deleted (backup too) and re-downloaded for fresh install.

I moved stuff to the online hosting (Shockbyte) and it seemed to work for me but console shows the below:
"28/11 22:31:58 [Error] Error receiving packet 23
28/11 22:31:58 [Error] io.netty.util.IllegalReferenceCountException: refCnt: 0"
When someone other than me tries to join...

**Comment by Linguardium** [comment]
did you set it to run with the correct java version and custom jar to launch the serverstarter jar?

download the serverpack from curseforge
once done, download https://github.com/TeamAOF/ServerStarter/releases/download/v2.4.1/serverstarter-2.4.1.jar
rename it custom-java21.jar (or custom-java17.jar)
Select the Custom JAR option from the Server Type dropdown
put all the serverpack files and the jar on your server
select the custom jar

**Comment by MrPlaner** [comment]
Well the server itself is working correctly - loads 1:1 just like it did with the local version.

I will tell them to do a fresh install of the modpack on CurseForge, maybe something didn't load correctly for them, as it works just fine for me after doing so.

Will update shortly.

**Comment by MrPlaner** [comment]
Alright!

Resetting the CurseForge modpack did the trick, 3 people joined with 0 issues on basically the first try.

Will close the issue with this one!
