### ISSUE TITLE
Very low ore generation

### ISSUE THREAD

**Issue by rockobonaparte** [TeamAOF/All-of-Fabric-7#32]
I'm trying to figure out if it's just using vanilla oregen but there seems to be a real lack of ore. If it's just vanilla, then that's really rough for technology mods that eat iron alive. I did some mining turtle quarrying and over approximate 250,000 blocks mined, I got something like 5 stacks of iron ore. Tech Reborn will eat one of those stacks just to get started from all the hammering. So I'm taking the opinion there needs to be some ore generation augmentations. I don't know what there is in 1.20.2 and Fabric mods that can actually do that though.

**Comment by rockobonaparte** [comment]
Talking around with some others, I'm thinking the iron ore generation is near vanilla rates. So it's not like it's bugged, but I've found that amount to be enough for any pack where they have some machines in particular.

**Comment by iteathen** [comment]
Versions 0.5.4 to 0.6.3 Ore generation seems normal and sufficient for a comfortable play experience.
