### ISSUE TITLE
Enchantment table will not open on server

### ISSUE THREAD

**Issue by iteathen** [TeamAOF/All-of-Fabric-7#36]
When a player attempts to open the enchantment table interface nothing happens. The server immediately generates an error.

"Cannot load class dev.shadowsoffire.apotheosis.ench.EnchModuleClient in environment type SERVER"

Tested on a clean install using All of Fabric 7 Server - 0.6.1
[latest.log](https://github.com/TeamAOF/All-of-Fabric-7/files/13062327/latest.log)

**Comment by Kazuhiko-Gushiken** [comment]
Will be fixed in the next hotfix update releasing soon. There was a problem with Zenith working on servers, though singleplayer it should work fine. Apologizes for this inconvenience.

**Comment by iteathen** [comment]
I got Zenith to work. I had to open a local game first then it would work on the server. Or at least it wouldn't crash/disconnect. I didn't not test Zenith directly.

**Comment by iteathen** [comment]
Fixed in 0.6.2

**Comment by iteathen** [comment]
.
