### ISSUE TITLE
Players are randomly invincible to seemingly everything

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#4]
We don't know how this happens at all, i'll upload log when I'll shut the server off.
We're 3 people, server lags sometimes quite a bit so maybe a problem related to lag?

**Comment by Trent2087** [comment]
Remove the login protection mod
logprot-fabric-1.20.1-3.1.jar
Will be removed in next update

**Comment by ImAK9** [comment]
Fixed in 0.2.0
