### ISSUE TITLE
Server mod recommendations

### ISSUE THREAD

**Issue by iteathen** [TeamAOF/All-of-Fabric-7#41]
These mods are really important for servers.

Chunky - pre-generate chunks
textile_backup - backups

**Comment by SubordinalBlue** [comment]
Agreed on the principal that a server should have some mods added; seems to be established policy not to include too much server-only stuff in the pack and leave that up to the server admin.

If you're on AoF Studio's discord server, you'll find the list of mods the official servers have added to them, pinned to the #all-of-fabric-6 channel.
