### ISSUE TITLE
Consider adding screen to startserver.sh?

### ISSUE THREAD

**Issue by iteathen** [TeamAOF/All-of-Fabric-7#42]
This works with what we have now but a script running a script is redundant. 

```
#/bin/bash
screen -S AOF7 ./startserver.sh
```

Without this the server will probably crash if the admins console session gets disconnected.

**Comment by SubordinalBlue** [comment]
Nice idea, but one is logging in remotely to start a server, why not screen the session?

Also, and I really don't know on this, but making screen part of the startserver script might bork on the typical hosting service where one doesn't have shell access, no?

**Comment by iteathen** [comment]
I agree, I like your thinking.

**Comment by SubordinalBlue** [comment]
Considering you're the first person even mention `screen` in AoF discussion, yeah, we're probably a rare case. Gonna close this. Always great to have input, suggestions, and feedback.
