### ISSUE TITLE
Recipe conflict, cannot make drying racks due to item shelves conflict

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#5]
https://github.com/TeamAOF/All-of-Fabric-7/assets/87911136/624d1ec4-699b-4f0e-a33c-8d50f87c01a0

Title says everything

**Comment by Trent2087** [comment]
Technically fixed in pack version 0.3.0 by adding Polymorph so you can select different recipe outputs when they conflict. Leaving this open as this is a band aid solution until we add Kubejs to fix recipe conflicts.

**Comment by SubordinalBlue** [comment]
Bump. Looks like this is done now, no?

**Comment by Kazuhiko-Gushiken** [comment]
Been fixed. Please update for fix.
