### ISSUE TITLE
[Mod Suggestion] Botania (Fabric/Quilt)

### ISSUE THREAD

**Issue by I0u0I** [TeamAOF/All-of-Fabric-7#52]
Would love to see a return of Botania, was great fun in AOF6 and it was now been updated to 1.20.1

**Comment by Teboran** [comment]
Same thing for Spectrum.

**Comment by Kazuhiko-Gushiken** [comment]
Very Soon™

**Comment by ImAK9** [comment]
Added in 1.0.0 update

**Comment by kendofriendo** [comment]
Guess I won't be playing that update. Way too OP.
