### ISSUE TITLE
No intuitive way to access the new quests, AOF7 1.0.0

### ISSUE THREAD

**Issue by fmbellomy** [TeamAOF/All-of-Fabric-7#55]
Currently upon loading into a fresh world on AOF7 1.0.0, the only way you have to access your quest tab is by pressing the default keybind of 'u.'
This is pretty rough UX as most players will expect to have an icon in the top left of REI or to be given a quest book item off of spawn.

**Comment by ImAK9** [comment]
Added buttons in 1.0.1 to the inventory screen
