### ISSUE TITLE
[Suggestion] Allow for Botania's Orechid to generate modded ores

### ISSUE THREAD

**Issue by Gronglegrowth** [TeamAOF/All-of-Fabric-7#61]
I would like for the Orechid (botania) to generate ores from other mods, as a magical alternative to quarries. This would add some more variation in acquisition of resources, instead of always going to tech. If wanted, I can make the needed jsons.

**Comment by Gronglegrowth** [comment]
[This PR](https://github.com/TeamAOF/All-of-Fabric-7/pull/62) has aformentioned jsons

**Comment by ImAK9** [comment]
Added in 1.0.2, much thanks for all the work getting it done!
