### ISSUE TITLE
Server Crash: "Accessing LegacyRandomSource from multiple threads" 

### ISSUE THREAD

**Issue by SiriusBYT** [TeamAOF/All-of-Fabric-7#7]
[crash-2023-08-22_18.48.13-server.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12410899/crash-2023-08-22_18.48.13-server.txt)

Crash dump ^

**Comment by James103** [comment]
Are you able to reproduce this crash with https://modrinth.com/mod/uwrad installed on the server? If so, please post the resulting crash report.

**Comment by SiriusBYT** [comment]
> Are you able to reproduce this crash with https://modrinth.com/mod/uwrad installed on the server? If so, please post the resulting crash report.

Will try later today, it crashes completely at random (at least we think) so it will be kinda tough to try to make it crash.

**Comment by SiriusBYT** [comment]
Can't seem to reproduce the crash, at least alone, maybe this has to do with my server being caught on fire with 3 players trying to generate chunks? God knows if this was patched in the recent versions

**Comment by Trent2087** [comment]
Haven't seen any more issues with this. So closing it now.
