### ISSUE TITLE
[Bug] "Portable Mass" quest has a reward, but no tasks.

### ISSUE THREAD

**Issue by Tanden22** [TeamAOF/All-of-Fabric-7#70]
In the "Getting Started" chapter of the quest book, the quest "Portable Mass", unlocked after "My arms are full!" has a reward attached to it (40 XP) but no tasks, making the quest non-completable.
![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/25508629/0991f1ef-c480-440d-bcce-919f771972fd)
![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/25508629/b169fbeb-2614-4d1b-b61d-012b26978e95)

**Comment by SubordinalBlue** [comment]
Doh! Will fix. Thank you!

**Comment by Kazuhiko-Gushiken** [comment]
@Tanden22 [fixed](https://github.com/TeamAOF/All-of-Fabric-7/commit/a952b8d5533fe1e607db4b2113bf2590920953cb).
