### ISSUE TITLE
Unable to craft Sky Steel Ingots

### ISSUE THREAD

**Issue by rrawk** [TeamAOF/All-of-Fabric-7#71]
I am unable to use in-world transformation methods to make Sky Steel from MEGA cells

Here is a link to the thread on their github that someone else posted 2 days ago
https://github.com/62832/MEGACells/issues/94

**Comment by fmbellomy** [comment]
Yeah it's been fixed in MEGA Cells since then, we're pretty much just waiting for AOF7 to update at this point.
It ended up being a conflict with GoFIsh.

**Comment by ImAK9** [comment]
Fixed in 1.0.0
