### ISSUE TITLE
Every Iron Cage Lamp from Create Deco does not have crafting recipes

### ISSUE THREAD

**Issue by Ogloppi** [TeamAOF/All-of-Fabric-7#75]
Please see the attached screenshot.

![2023-12-17_12 09 23](https://github.com/TeamAOF/All-of-Fabric-7/assets/10729783/674fe15c-117a-47f2-ba60-81ee3904d3a8)

**Comment by Kazuhiko-Gushiken** [comment]
@Ogloppi added recipes for Iron Cages AND the Copper Cages (because they didnt have any either)

https://github.com/Kazuhiko-Gushiken/All-of-Fabric-7/commit/523e9c7e0f719d2247988ac346afabddd4fcef1b
