### ISSUE TITLE
[BUG] Possible to get fortune levels up to level 127

### ISSUE THREAD

**Issue by KrazyMiner001** [TeamAOF/All-of-Fabric-7#77]
By putting an endersurge gem from zenith of any type on a spectrum workstaff of any type it is possible to get a fortune level up to 127 on the workstaff, which can be extracted into a book using the spectrum enchanter.

# Steps to reproduce:
 
 - Reforge any spectrum workstaff such that it has a gem slot
 - Apply any level of Endersurge gem from zenith
 - Use workstaff's ability to change enchantment between fortune and something else, each time the fortune level is increased by the bonus of the endersurge gem
 - If wanted as book use gilded book in spectrum enchanter to extract the high level fortune as book

![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/57949410/1351f4f2-1be6-4cff-9940-6ca9126afb06)
![image](https://github.com/TeamAOF/All-of-Fabric-7/assets/57949410/c5b03552-9424-43af-8ffa-052a4cff7d0c)

**Comment by SubordinalBlue** [comment]
Not sure if that's really a bug or a feature, even if accidental.
Over-enchanting was a well liked mechanic in AoF6, though that arose from a different intersection of mods interacting.
