### ISSUE TITLE
client crash when viewing guide

### ISSUE THREAD

**Issue by Natanaelel** [TeamAOF/All-of-Fabric-7#8]
hover over for example budding certus quartz in jei, hold w, crash
[crash-2023-08-22_19.13.49-client.txt](https://github.com/TeamAOF/All-of-Fabric-7/files/12411207/crash-2023-08-22_19.13.49-client.txt)

**Comment by SiriusBYT** [comment]
Can confirm this is a problem

**Comment by Trent2087** [comment]
Fixed in pack version 0.3.0 by removing the Starlight mod as it was conflicting, and in 1.20 doesn't really benefit the client anymore.
