### ISSUE TITLE
[Bug] Tech Reborn Grinder - no dust recipes using raw ores

### ISSUE THREAD

**Issue by charlotteroose** [TeamAOF/All-of-Fabric-7#86]
Currently the recipe for ore dust using the Tech Reborn Grinder takes ore blocks, however it doesn't take raw iron, which makes this machine largely useless, unless you're needing to grind already smelted materials, or if you have a silk touch pickaxe (not super practical for farming ore).
E.g. rather than turn 1x raw iron into 2x iron dust (and make 2x iron ingots), it only has a recipe to turn 1x iron ore into 2x raw iron (which could go to 2x iron ingots) - at the use of a silk touch pickaxe.
Currently needing to use the Industrial Revolution Macerator to make 1-2 dust per raw ore, which is a bit of a pain.
I'm hoping this makes sense and that it is unintentional and will be fixed soon? Thanks!
![Screenshot 2023-12-31 205148](https://github.com/TeamAOF/All-of-Fabric-7/assets/16271107/f27ef4cb-9c14-43c2-8aed-0fe3e74b9df8)

**Comment by SubordinalBlue** [comment]
That's standard TR; it doesn't even _have_ (add) iron dust to the game on it's own.

However, Modern Industrialization will macerate raw iron to 1.5 dusts (50% chance of 1, 50% of 2); after first maceration pass yielding 3 raw iron ores per ore block, that's 4.5 dusts per ore block.
